services:
  app:
    build:
      context: ./app
    restart: unless-stopped
    logging:
      options:
        max-size: 100m

  db:
    image: postgres:16.8-alpine
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
